import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: "#081226",
  },
  appFadeLayer: {
    flex: 1,
  },
  tutorialOverlay: {
    flex: 1,
    backgroundColor: "rgba(5, 12, 27, 0.72)",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  tutorialCard: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: "#122847",
    borderRadius: 18,
    paddingVertical: 22,
    paddingHorizontal: 18,
  },
  tutorialTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#F8F8F8",
    marginBottom: 10,
  },
  tutorialText: {
    color: "#D3DEF3",
    fontSize: 15,
    lineHeight: 22,
    marginBottom: 8,
  },
  tutorialButton: {
    marginTop: 10,
    backgroundColor: "#54B7E5",
    paddingVertical: 11,
    borderRadius: 12,
    alignItems: "center",
  },
  tutorialButtonText: {
    color: "#0B1A32",
    fontWeight: "800",
    fontSize: 15,
  },
  splashContainer: {
    position: "absolute",
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: "#081226",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
    zIndex: 10,
  },
  splashCard: {
    width: "100%",
    maxWidth: 360,
    backgroundColor: "#122847",
    borderRadius: 18,
    paddingVertical: 28,
    paddingHorizontal: 22,
    alignItems: "center",
  },
  splashTitle: {
    fontSize: 36,
    fontWeight: "800",
    color: "#F8F8F8",
    marginBottom: 6,
  },
  splashSubtitle: {
    color: "#B8C7E0",
    fontSize: 15,
    marginBottom: 16,
  },
  loginContainer: {
    flex: 1,
    backgroundColor: "#081226",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  loginCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#122847",
    borderRadius: 18,
    padding: 22,
  },
  loginTitle: {
    fontSize: 34,
    fontWeight: "800",
    color: "#F8F8F8",
    marginBottom: 8,
  },
  loginSubtitle: {
    color: "#B8C7E0",
    fontSize: 15,
    marginBottom: 16,
  },
  loginInput: {
    width: "100%",
    backgroundColor: "#213B66",
    color: "#F8F8F8",
    paddingHorizontal: 12,
    paddingVertical: 11,
    borderRadius: 10,
    marginBottom: 10,
    fontSize: 16,
  },
  passwordRow: {
    width: "100%",
    position: "relative",
    justifyContent: "center",
    marginBottom: 10,
  },
  passwordInput: {
    marginBottom: 0,
    paddingRight: 46,
  },
  passwordToggleButton: {
    position: "absolute",
    right: 10,
    top: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  loginButton: {
    backgroundColor: "#3C86F0",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 4,
  },
  disabledButton: {
    opacity: 0.6,
  },
  loginButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700",
  },
  loginError: {
    color: "#FFD4D4",
    marginBottom: 10,
    fontSize: 13,
  },
  authSwitchButton: {
    alignItems: "center",
    marginTop: 12,
    paddingVertical: 8,
  },
  authSwitchText: {
    color: "#B8D6FF",
    fontSize: 14,
    fontWeight: "600",
  },
  container: {
    flex: 1,
    backgroundColor: "#0B1A32",
    paddingTop: 50,
    alignItems: "center",
  },
  focusModeContainer: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 16,
  },
  focusModeHeader: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
    paddingHorizontal: 4,
  },
  focusModeStatus: {
    color: "#B8C7E0",
    fontSize: 13,
    fontWeight: "600",
  },
  focusModeExit: {
    color: "#B8D6FF",
    fontSize: 14,
    fontWeight: "700",
    paddingVertical: 6,
    paddingHorizontal: 10,
    backgroundColor: "#1A345D",
    borderRadius: 10,
    overflow: "hidden",
  },
  focusBoardWrap: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  title: {
    fontSize: 32,
    fontWeight: "700",
    color: "#F8F8F8",
    marginBottom: 16,
  },
  pageHeaderWrapper: {
    width: "90%",
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    backgroundColor: "#122847",
    borderWidth: 1,
    borderColor: "#274B7A",
  },
  pageHeaderImageArea: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    paddingTop: 14,
    paddingBottom: 8,
    backgroundColor: "#16365D",
  },
  pageHeaderImage: {
    width: "85%",
    height: 96,
  },
  pageHeaderOverlay: {
    backgroundColor: "#122847",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  pageHeaderTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#F8F8F8",
    textAlign: "center",
  },
  pageHeaderSubtitle: {
    marginTop: 2,
    color: "#D3DEF3",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
  },
  panel: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#122847",
  },
  panelRow: {
    width: "90%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    marginBottom: 12,
  },
  panelText: {
    color: "#F8F8F8",
    fontSize: 14,
    fontWeight: "600",
  },
  statusText: {
    color: "#FFD700",
  },
  actionButton: {
    backgroundColor: "#3C86F0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 8,
    minWidth: 110,
    alignItems: "center",
  },
  logoutButton: {
    backgroundColor: "#D14343",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginBottom: 8,
    minWidth: 110,
    alignItems: "center",
  },
  startButton: {
    marginTop: 10,
    backgroundColor: "#54B7E5",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  editorInfo: {
    width: "90%",
    padding: 12,
    borderRadius: 12,
    backgroundColor: "#122847",
    marginBottom: 12,
    alignItems: "center",
  },
  levelNameInput: {
    width: "100%",
    backgroundColor: "#213B66",
    color: "#F8F8F8",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    marginBottom: 8,
    fontSize: 16,
  },
  resetText: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  board: {
    width: "90%",
    aspectRatio: 1,
    borderRadius: 16,
    backgroundColor: "#0A1630",
    padding: 6,
  },
  focusModeBoard: {
    width: "98%",
    padding: 3,
  },
  row: {
    flex: 1,
    flexDirection: "row",
  },
  cell: {
    flex: 1,
    margin: 2,
    borderRadius: 6,
    backgroundColor: "#213B66",
    alignItems: "center",
    justifyContent: "center",
  },
  focusModeCell: {
    margin: 1,
    borderRadius: 5,
  },
  cellRevealed: {
    backgroundColor: "#D6DCE5",
  },
  cellFlagged: {
    backgroundColor: "#F08B3A",
  },
  cellMine: {
    backgroundColor: "#D14343",
  },
  cellDesignMine: {
    backgroundColor: "#4A6FB8",
  },
  cellText: {
    color: "#F8F8F8",
    fontSize: 16,
    fontWeight: "700",
  },
  cellTextEditor: {
    color: "#FFFFFF",
  },
  cellTextRevealed: {
    color: "#1B2438",
  },
  hint: {
    marginTop: 14,
    color: "#B8C7E0",
    fontSize: 14,
  },
  levelItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    width: "100%",
  },
  levelButton: {
    flex: 1,
    backgroundColor: "#3C86F0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
    marginRight: 10,
    minHeight: 44,
  },
  deleteButton: {
    backgroundColor: "#D14343",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  levelList: {
    width: "90%",
    maxHeight: 300,
    marginVertical: 10,
  },
});
